name: Maven CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Deploy to Tomcat Server
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
           echo "$SSH_KEY" > key.pem
           chmod 600 key.pem

            # Upload WAR/JAR to home directory (~) on EC2
           scp -i key.pem -o StrictHostKeyChecking=no target/*.war $TOMCAT_USER@$TOMCAT_HOST:~

           # SSH in and move file with sudo, set ownership, restart Tomcat
           ssh -i key.pem -o StrictHostKeyChecking=no $TOMCAT_USER@$TOMCAT_HOST << EOF
           sudo mv ~/$(basename target/*.war) /opt/tomcat/webapps/
           sudo chown tomcat:tomcat /opt/tomcat/webapps/$(basename target/*.war)
           sudo systemctl restart tomcat
           EOF
